version: "3.7"
services:
  dbpsud:
    image: postgres:12.2
    deploy:
      restart_policy:
        condition: none
    environment:
      POSTGRES_PASSWORD: best
      POSTGRES_USER: best
      POSTGRES_DB: best
    ports:
      - 5432:5432